---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  # Resource is associated with the previously created namespace.
  namespace: locust
spec:
  # Specify the required number of worker pods.
  replicas: 2
  selector:
    matchLabels:
      app: locust
      component: worker
  template:
    metadata:
      labels:
        app: locust
        component: worker
    spec:
      containers:
        - name: locust-worker
          # Use our custom build image from ECR containing our tests.
          image: 111122223333.dkr.ecr.us-east-2.amazonaws.com/locust:master
          # Args will be different between control and workers.
          # Notice the input test file matches one of the scripts included in
          # the root directory of the custom image we built (script1.py).
          # Notice the master host is being set as control-locust from our 
          # control deployment.
          args:
            [
              "-f=./script1.py",
              "--worker",
              "--master-host=locust-control"
            ]
          # Notice no ports need to be opened for workers.
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
