---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  # Resource is associated with the previously created namespace
  namespace: locust
data:
  # The script1 key will hold the value for the first test
  script1: |-
    from locust import HttpUser, task, between

    class test(HttpUser):
        wait_time = between(1, 3)

        @task
        def initial_request(self):
            self.client.get("/")
  # The script2 key will hold the value for the second test
  script2: |-
    from locust import HttpUser, task, between

    class test(HttpUser):
        wait_time = between(2, 4)

        @task
        def initial_request(self):
            self.client.get("/")